apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: python-rollout
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: python-active
      previewService: python-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python
          image: goutam24/bluegreen-python:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-active
spec:
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-preview
spec:
  selector:
    app: python-app
  ports:
    - port: 8081
      targetPort: 8080

